CREATE TABLE `event` (
	`event_id` INT PRIMARY KEY AUTO_INCREMENT,
	`name` TEXT NOT NULL,
	`short_name` VARCHAR(64) NOT NULL,
	`event_start` TIMESTAMP NOT NULL DEFAULT 0,
	`event_end` TIMESTAMP NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
